Added a script to send commits
codex-team/hawk.releases pull request #1
Opened 2021-08-26 18:17 UTC by GeekaN2

Added a script to make it a little easier to send comments to the collector. The first step towards cli

2021-08-26 18:32 UTC, neSpecc requested changes

2021-08-26 18:32 UTC, neSpecc commented on README.md
> +| `-ce` \| `--collectorEndpoint` | No | Endpoint to send release data. |
Add example of call

2021-08-27 13:08 UTC, nikmel2803 approved these changes

2021-09-03 10:26 UTC, talyguryn approved these changes

2021-09-03 10:48 UTC, merged